# Site information
title:        D. Nathan Dillon
description:  The portfolio website of D. Nathan Dillon.
url:          https://dnathandillon.com

# Social
twitter_username: NatoriousFAT
github_username:  natedillon

# Global configuration
source: src
destination: build
permalink: pretty
include:
exclude:
  - assets
keep_files:
  - assets

# Collections
collections:
  pages:
    output: true
    permalink: /:path/
  work:
    output: true
    permalink: /:collection/:path/
  conferences:
    output: true
    permalink: /:collection/:title/

# Front matter defaults
defaults:
  -
    scope:
      path: ''
      type: pages
    values:
      layout: page
  -
    scope:
      path: ''
      type: work
    values:
      layout: project
  -
    scope:
      path: ''
      type: conferences
    values:
      layout: conference

# File paths
path:
  img:                    /assets/img
  project_thumb_default:  /assets/img/projects/thumb.svg
