# Site settings
title: D. Nathan Dillon
email: nate@natedillon.com
description: The portfolio website of D. Nathan Dillon.
baseurl: ''
url: 'http://dnathandillon.com'
twitter_username: NatoriousFAT
github_username:  natedillon

# Global configuration
exclude:
  - '_css'
  - 'Gemfile'
  - 'Gruntfile.js'
  - 'node_modules'
  - 'package.json'
  - 'README.md'
include:
keep_files:
  - 'css'

# Build settings
markdown: kramdown

# Outputting
permalink: /:title/

# Where things are
collections:
  projects:
    output: true
    permalink: /work/:title/
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: 'post'
      permalink: '/blog/:year/:month/:day/:title/'
  -
    scope:
      path: '_projects'
      type: 'projects'
    values:
      layout: 'project'
