# Site information
title:        D. Nathan Dillon
description:  The portfolio website of D. Nathan Dillon.
url:          http://dnathandillon.com

# Social
twitter_username: NatoriousFAT
github_username:  natedillon

# Permalinks
permalink: pretty

# Global configuration
exclude:
  - src
  - CNAME
  - Gemfile
  - Gruntfile.js
  - node_modules
  - package.json
  - README.md

# Collections
collections:
  conferences:
    output: true
    permalink: /about/conferences/:title/

# Defaults
defaults:
  -
    scope:
      path: ""
      type: pages
    values:
      layout: page
  -
    scope:
      path: work
      type: pages
    values:
      layout: project
  -
    scope:
      path: ""
      type: conferences
    values:
      layout: conference

# File paths
path:
  img:                    /dist/img
  project_thumb_default:  /dist/img/projects/thumb.png
