# Site settings
title: D. Nathan Dillon
email: nate@natedillon.com
description: The portfolio website of D. Nathan Dillon.
baseurl: ""
url: "http://dnathandillon.com"
twitter_username: NatoriousFAT
github_username:  natedillon

# Global configuration
exclude: ['node_modules']

# Build settings
markdown: kramdown
theme: minima
